### ISSUE TITLE
Cannot parse tag split into several lines - offered solution

### ISSUE THREAD

**Issue by pedjas** [jbowens/jBBCode#31]
I found out that if I split long BBCode tag into several lines, jBBCode cannot parse properly.

I fixed it by simple change in Tokenizer.php

On line 31 there is a command:
`array_push($this->tokens, substr($str, $strStart, $index - $strStart));`

Replace it with:
`array_push($this->tokens, trim(preg_replace('/\s+/', ' ', substr($str, $strStart, $index - $strStart))));`

And that is all. After this fix you can split tag into several lines.

I hope someone could add this fix into the git source. I do not use git.

**Comment by pedjas** [comment]
This fix I posted produced another bug - spaces around BBCtags are removed too...

**Comment by Kubo2** [comment]
@pedjas Please, find another solution. Regular expressions are not accepted in this project.

**Comment by pedjas** [comment]
Whz not?!?! That is rather strange....

**Comment by Kubo2** [comment]
@pedjas You read, it is mentioned on the top of [README.md](README.md).

**Comment by jbowens** [comment]
@pedjas Regular expressions are often slow and difficult to maintain. The goal of this project was to create a BBCode parser that would be faster than regexp-based parsers.

**Comment by pedjas** [comment]
I missed that part.
Well, then I do not know how to do it in faster way, so I would report this issue as an bug.

Splitting BBC in several lines is quite common and jBBCode cannot handle that.

**Comment by DaSourcerer** [comment]
Uhm … isn't this fixed with #43?

**Comment by Kubo2** [comment]
I think yes.

/cc @jbowens @pedjas One of you please close this.
