### ISSUE TITLE
Let ParserException inherit from DomainException (or replace it entirely)

### ISSUE THREAD

**Issue by DaSourcerer** [jbowens/jBBCode#70]
This has bugged me for a while now: `ParserException` is by its semantics a clear candidate for inheriting from [`\DomainException`](http://php.net/manual/class.domainexception.php) (see also [this SO discussion](http://stackoverflow.com/questions/1102979/when-would-you-throw-a-domainexception-in-php)) instead of the generic \Exception.

However, given that `ParserException` is not exposed to any codepaths outside the parser, it would make sense to scrap it entirely and reduce the weight of the codebase. Any thoughts?

**Comment by shmax** [comment]
`ParserException` was my doing. I have no particular attachment to it, it just seemed to make sense at the time, but as you've noticed wasn't otherwise very carefully thought out. If you want to replace, remove or re-parent it I for one will have no objection.
