### ISSUE TITLE
Parser doesn't handle spaces in font-family options

### ISSUE THREAD

**Issue by xorinzor** [jbowens/jBBCode#71]
The SCEditor creates a tag such as `[font=Comic Sans MS]`, the jBBCode parser however only returns `Comic` as the attribute.

Also when adding quotes it only returns `Comic`.

**Comment by shmax** [comment]
It would be helpful for us to see some code. This seems to work just fine for me:

```
$parser = new \JBBCode\Parser();
$parser->addCodeDefinition(\JBBCode\CodeDefinition::construct("font",
	'<span style="font-family:{option}">{param}</span>',
	true
));
$parser->parse('This contains a [font=Comic Sans MS]font[/font].');
echo $parser->getAsHTML();
```

**Comment by xorinzor** [comment]
@shmax I copied that code and it still doesn't work for me, same issue.

I'm running 1.3.0, that's the latest version, right?

**Comment by xorinzor** [comment]
hmm, with quotes it did work though, I guess it's messing up somewhere, glad to know it works fine.

**Comment by shmax** [comment]
Well, it looks like you still have a point about the no-quotes syntax; turns out I had an older version.

**Comment by shmax** [comment]
It looks like it broke with this PR:
https://github.com/jbowens/jBBCode/pull/25

@Schlaefer any thoughts?
