### ISSUE TITLE
multiple tag options

### ISSUE THREAD

**Issue by abetis** [jbowens/jBBCode#83]
Hi. Hope that great project is still maintained...
I was hopping to add a support for multiple tag options, specifically for img ALT text in format of:
[img alt="text" width="100" height="200"]url[/img]

Defined CodeDefinition class and start playing with the code.
Unfortunately the parser didn't get to my code since the tag name is assumed to be up to the "]" character or the "=" where the assumption is that the format will always be [tag=option].
        /* There could be an attribute. */
        $tagPieces = explode('=', $tagContent);
        $tmpTagName = $tagPieces[0];

Before I deep dive into the parser code...
Is there anything that was already done in that direction?

Thanks.

**Comment by shmax** [comment]
Support for multiple tag parameters was added [years ago](https://github.com/jbowens/jBBCode/pull/16). We'd have to see your `CodeDefinition` implementation to be of any help.

**Comment by abetis** [comment]
Hmmm... Looks like I'm using a very old code...
Thanks.
