### ISSUE TITLE
 How to encode?

### ISSUE THREAD

**Issue by joelmiguelvalente** [jbowens/jBBCode#87]
Hola, estoy buscando una forma de poder codificar ya sea con **urlencode** o **base64_encode**, pero si uso una de las funciones me devuelve `{option}` y no la url que deseo.
¿Como puedo hacerlo?
=== Traduction ===
Hello, I'm looking for a way to be able to encode with either **urlencode** or **base64_encode**, but if I use one of the functions it returns me `{option}` and not the url that I want.
How can I do it?

**Comment by Kubo2** [comment]
Hola @joelmiguelvalente,

¿podrías agregar acá el código relevante que no te sale de la manera que quieras, y describir un poquito más lo que deseás que haga? Yo en cuanto regrese a casa, trataré de ayudarte.
